---
- name: Reload nfs exports
  ansible.builtin.command:
    cmd: exportfs -ra
  become: true

- name: Restart nfs server
  ansible.builtin.service:
    name: "{{ storage_nfs_server_service }}"
    state: restarted
  become: true
